 
// the configured options and settings for raw2dng
#define RAW2DNG_VERSION_MAJOR @RAW2DNG_VERSION_MAJOR@
#define RAW2DNG_VERSION_MINOR @RAW2DNG_VERSION_MINOR@
#define RAW2DNG_VERSION_PATCH @RAW2DNG_VERSION_PATCH@

#define RAW2DNG_VERSION_MAKE(a,b,c) #a"."#b"."#c
#define _RAW2DNG_VERSION_MAKE(a,b,c) RAW2DNG_VERSION_MAKE(a,b,c)
#define RAW2DNG_VERSION_STR _RAW2DNG_VERSION_MAKE(RAW2DNG_VERSION_MAJOR,RAW2DNG_VERSION_MINOR,RAW2DNG_VERSION_PATCH)
